config/routes.rb
Leatherstore::Application.routes.draw do
 

devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders

  resources :line_items

  resources :carts

  resources :categories

  get "home/index"
  

  resources :products

  root :to => 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
 
 
  has_many :line_items, :dependent => :destroy
  

def paypal_url(return_url)
  values = {
    :business => 'seller_1354927476_biz@gmail.com',
    :cmd => '_cart',
    :upload => 1,
    :return => return_url,
    :invoice => id
  }
  line_items.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.product.price,
      "item_name_#{index+1}" => item.product.name,
      "quantity_#{index+1}" => item.quantity
    })
  end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end


  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
     current_item.quantity += 1
    else
       current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  load_and_authorize_resource
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    # begin
     
     @cart = Cart.find(params[:id])
  # rescue ActiveRecord::RecordNotFound
    # logger.error "Attempt to access invalid cart #{params[:id]} "
    # redirect_to products_path , :notice => 'Invalid Cart'
  # else

    respond_to do |format|
      format.html # show.html.erb
       # format.js 
      format.json { render :json => @cart }
    # end
  end
  end
  
    

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, :notice => 'Cart was successfully created.' }
        format.json { render :json => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.json { render :json => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, :notice => 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to products_url, :notice => ' Your cart has been emptied' }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
    def current_cart
  Cart.find(session[:cart_id])
rescue ActiveRecord::RecordNotFound
  @cart= Cart.create
  session[:cart_id] = @cart.id
 
  @cart
  
end

    def subtotal(cart)
    lineitems = cart.line_items
     @linetotal = 0
    lineitems.each do |li|
     @linetotal = @linetotal + litotal(li)
      end 
     @linetotal 
    end
    def litotal(item)
      item.product.price*item.quantity
    end
    def shipping(cart)
      shippingcharges =0
     lineitems = cart.line_items
     @count = 0
     lineitems.each do |li|
       @count = @count+li.quantity
      end
     shippingcharges = @count*3.99    
      shippingcharges
    end
    def tax(cart)
      taxamt = subtotal(cart)*0.06     
    end
    def total(cart)
      @total = subtotal(cart)+shipping(cart)+tax(cart)
    end
 
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/_shopcart.html.erb
<% if session[:cart_id].nil?  %>
  <%@cart= Cart.create%>
  <%session[:cart_id] = @cart.id%>
  <div id="cart"><%= link_to " Your Shopping Cart", cart_path(session[:cart_id]) %>
<% else%>
<div id="cart"><%= link_to " Your Shopping Cart", cart_path(session[:cart_id]) %>
<%end%>	
<div class="cl"> </div>
<% @current_cart = current_cart %>
<% @items = item(@current_cart)%>
<% @total = (total(@current_cart))*100.to_i/100.0 %>
<span>Cost:<strong><%=  number_to_currency(@total)%></strong></span> 
<span>Items:<strong> <%= @items %></strong></span>

app/views/carts/_shoptable.html.erb
<fieldset>

<table id = "shopping-bar">
<tbody>
<tr class="bag-bar" >

<th class="prod-description" scope="col">Product Description</th>
<th class="prod-price" scope="col" >Price</th>
<th class="prod-quantity" scope="col">Quantity</th>
<th class="prod-total" scope="col">Total</th>
<th class="prod-actions" scope="col">Actions</th>
</tr>

<% @cart.line_items.each do |item|%>

<tr >	
<td class="prod-description" scope="row" >
<div class = "item-thumb"><%= image_tag(item.product.image,:size => "50x50")  %> </div>	
	<ul>
		<li> <%= link_to truncate(item.product.name) ,item.product %></li>
		<li> Brand : </li></ul>	
	</td>
	<td class="prod-price" scope="row" align="center"> <%= content_tag(:p, number_to_currency(item.product.price))%></td>
	<td class="prod-quantity" scope="row" align="center"><%= item.quantity %> </td>
	<td class="prod-total" scope="row" align="center"><%= number_to_currency(litotal(item))%></td>
	<td class="prod-actions" scope="row" align="center">
		<ul>
			<li><%= link_to 'Edit this item', product_path(item.product.id) %> </li>
			<li><%= link_to 'Remove', line_item_path(item.id) ,:method => :delete %></li>
		</ul>
	</td>
</tr>
<%end%>
</tbody>
</table>
</fieldset>

<fieldset id = "charge">

<div id="charge-container" align="right">
<ul id="charges">
<li id="subtotal"><b>Subtotal: </b><%=number_to_currency(subtotal(@cart))%></li>
<li id="shipping"><b>Estimated Shipping: </b> <%=number_to_currency(shipping(@cart))%></li>
<li id="tax"><b>Tax: </b> <%=number_to_currency(tax(@cart))%></li>
<li id="total"><b>Total: </b> <%=number_to_currency(total(@cart))%></li>



<%= button_to "Checkout", @cart.paypal_url(products_url) %>


<%= button_to "Empty Cart", @cart, :method => :delete, :confirm =>"Are you sure?"%>
</ul>
</div>
</fieldset>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<% if can? :update,@cart%>
<%= link_to 'Show', @cart %> 
<%end%>
<% if can? :update,@cart%>
<%= link_to 'Back', carts_path %>
<%end%>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
  	<% if can? :update,@cart%>
    <td><%= link_to 'Show', cart %></td>
    <%end%>
    <% if can? :update,@cart%>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <%end%>
    <% if can? :delete,@cart%>
    <td><%= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  <%end%>
  </tr>
<% end %>
</table>

<br />
<% if can? :create,@cart%>
<%= link_to 'New Cart', new_cart_path %>
<%end%>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<% if can? :update,@cart%>
<%= link_to 'Back', carts_path %>
<%end%>

app/views/carts/show.html.erb
<div>
	<div id = "content">
	<p id="notice"><%= notice %></p>
<div id = "show">
<%= render :partial => "shoptable"%>
</div>
</div>

</div>

app/views/carts/show.js.erb
<!-- $('#show').html("<%= escape_javascript(render(:partial =>'shoptable')) %>");  -->