config/routes.rb
Leatherstore::Application.routes.draw do
 

devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders

  resources :line_items

  resources :carts

  resources :categories

  get "home/index"
  

  resources :products

  root :to => 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  load_and_authorize_resource
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
      format.js 
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_products.html.erb
<h3>
  <%= link_to @category.name, @category , :remote => true %>
</h3>
<% @products = @category.products %>
<div class="cl"> </div>
<ul>
	<% @products.each do |product|%>
<li>

<%= image_tag(product.image,:size => "150x150")  %>

<div class="product-info">
	<h3 align="center"> <%= link_to truncate(product.name), product%> 
		<% if can? :update,product%>
		<%= link_to '| Edit |', edit_product_path(product) %>
		<%end%>
		<% if can? :destroy,product%>
			<%= link_to ' Delete  | ', product, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
			<%end%>
		</h3>
	</div>	
</li>
<%end%>
</ul>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>
<% if can? :update,@category%>
<%= link_to 'Show', @category %> 
<%end%>
<% if can? :update,@category%>
<%= link_to 'Back', categories_path %>
<%end%>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <% if can? :update,@category%>
    <td><%= link_to 'Show', category %></td>
    <%end%>
    <% if can? :update,@category%>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <%end%>
    <% if can? :delete,@category%>
    <td><%= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
 <%end%>
  </tr>
<% end %>
</table>

<br />
<% if can? :create,@category%>
<%= link_to 'New Category', new_category_path %>
<%end%>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<% if can? :update,@category%>
<%= link_to 'Back', categories_path %>
<%end%>

app/views/categories/show.html.erb
<div>
<div id = "content">
<p id="notice"><%= notice %></p>
	<div class= "products">		
		<%= render :partial => "products"%>	
</div>
	</div>

<div id="sidebar">
	<div class = "box search">
		<h2>Search by<span></span></h2>		
		<div class="box-content">
	 <%= form_tag products_path, :method => :get, :remote => true  do %>
			<%= label_tag "Keyword"%>	
<%=text_field_tag :search,params[:search],:class=> 'field'%>
 	<%=submit_tag "Search", :name => nil %>  
    <%end%>
   
		</div> 
	</div>

</div>



<% if can? :update,@category%>
<%= link_to 'Edit Category', edit_category_path(@category) %> 
<%end%>
<% if can? :update,@category%>
<%= link_to 'Back to Categories', categories_path %>
<%end%>

app/views/categories/show.js.erb
$('.products').html("<%= escape_javascript(render(:partial =>'products')) %>"); 